### ISSUE TITLE
Built-in stylesheets break Bootstrap-3 layout, when included __after__ Bootstrap

### ISSUE THREAD

**Issue by kostia** [madebymany/sir-trevor-rails#21]
Hello,

following line from the built-on stylesheets breaks my app's layout (Bootstrap-3), when included **after** Bootstrap styles:

``` css
body { margin: 0; font-size: 1em; line-height: 1.4; }
```

Kind regards,
Kostia
