### ISSUE TITLE
Built-in stylesheets break Bootstrap-3 layout, when included after Bootstrap

### ISSUE THREAD

**Issue by kostia** [madebymany/sir-trevor-rails#22]
Hello,

following line from the built-on stylesheets breaks my app's layout (Bootstrap-3), when included __after__ Bootstrap styles:

```css
body { margin: 0; font-size: 1em; line-height: 1.4; }
```

Kind regards,
Kostia
